language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - cp build-tools/travis-ci/.atoum.php .atoum.php
  - sed -i s/COVERALLS_TOKEN/$COVERALLS_TOKEN/ .atoum.php
script:
    - bin/atoum
    - bin/coke